const images: Record<string, string> = {
  "freeaipoweredcmsmigrationmigrateyourwebsitefast":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/free-ai-cms-migration.jpg?w=360",
  "bestacquiaalternativesin2026enterprisedxpscompared":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/alternatives-acquia-2026-jahia.png?w=360",
  "whatisanaicmshowtochooseoneforaiworkflows":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/ai-cms.jpg?w=360",
  "headlesscmspersonalizationhowtodelivertrulyadaptiveexperiences":
    "/files/live/sites/jahiacom/files/social%20media/jahia-cms?w=360",
  "bestdrupalalternativesin2026enterprisecmsanddxpcompared":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/best-alternative-drupal.jpg?w=360",
  "howtocreateanextranetthestepstoscopeandsucceedwithyourproject":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/create-an-extranet.jpg?w=360",
  "extranetsolutionhowtochoosetherightplatformforyourclientspartnersandsuppliers":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/web-portal.png?w=360",
  "agenticaiincontentmanagementwhatyourcmsneedsin2026":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/agentic-ai-in-content-management.jpg?w=360",
  "howtobuildawebsitepersonalizationstrategy":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/web-personalization-with-a-strong-cms.png?w=360",
  "websitepersonalizationstrategyexamplesandbestpracticestoboostconversions":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/website-personalization_-strategy-examples-best-practices.svg",
  "whatisawebportaldefinitionexamplesenterpriseusecases":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/12-2022/interface-portail-web.jpg?w=360",
  "whatisaheadlesscmsthetrueheadlesscmsdefinition":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/AdobeStock_239340937-copie.jpg?w=360",
  "gdprsovereigntywhyyourchoiceofcmsmatters":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/GDPR-sovereignty/gdpr-sovereignty-why-your-choice-of-cms-matters.jpg?w=360",
  "8bestalternativestoadobeaemin2026cmsdxpcompared":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Logos/aem-alternative-jahia.jpg?w=360",
  "jahiaatthedigitalsovereigntysummit2026boothc13":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/salon-souverainete-conference.jpg?w=360",
  "cmsheadlessvscmstraditionalwhichisbestforyourbrand":
    "/files/live/sites/jahiacom/files/blog/headless%20vs%20tradi/web-development-for-headless-and-traditional-cms?w=360",
  "jahiaatcrmday2026inparis":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cozendo-coffee-break-1177540.jpg?w=360",
  "top7alternativestositecorein2026":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Top%207%20alternatives%20to%20Sitecore%20in%202025.jpg?w=360",
  "nasaispublishingfromspacewithjahia":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/earth-nasa-artemis-ii-april-2026.jpg?w=360",
  "jahiajoinslafrenchtech":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/en_jahiaxfrenchtech_horizontale_1350x1080-enx.png?w=360",
  "websitemigrationforenterprisessecuringyourwebsiteandseo":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cms-and-website-migration-jahia.jpg?w=360",
  "jahiafromthefield1productupdateswhatsnext":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/banniere-generique-newsletter-produitx2.png?w=360",
  "whatisadynamicwebsite":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/what%20is%20a%20dynamic%20website.jpg?w=360",
  "howiusedaitodevelopajahiamoduleinjavascriptinrecordtime":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/ia%20to%20develop%20jahia%20module%20in%20JS.jpg?w=360",
  "xpplatformtheagileandsovereignsolutionfordeliveringunifieddigitalexperiences":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/xp%20platform.jpg?w=360",
  "9questionstoaskyourselfwhenchoosingamultisitecms":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/9%20questions%20to%20ask%20when%20choosing%20a%20multisite%20cms.jpg?w=360",
  "whatiscloudcontentmanagement":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/what%20is%20cloud%20content%20management%20-%20jahia.jpg?w=360",
  "everythingyouneedtoknowaboutcloudcms":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cloud-connect.jpg?w=360",
  "thepowerofmultisitecmsbenefitskeyfeaturesandbestpractices":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/The%20power%20of%20multisite%20CMS%20benefits-min.jpg?w=360",
  "10benefitsofdigitalassetmanagementdamin2026":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/dam%20vs%20dms%20-%20jahia.jpg?w=360",
  "whatisdigitalassetmanagementdam":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Digital%20Asset%20Management%20(DAM).png?w=360",
  "enterprisecmsvssimplecmswhatsthedifference":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/simple%20cms%20vs%20enterprise%20cms.jpg?w=360",
  "enterprisecmsdefinitionkeyfeaturesandbenefits":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/what%20is%20enterprise%20cms.jpg?w=360",
  "10strategiccriteriaforchoosingthebestenterprisecms":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/10%20keys%20choosing%20the%20best%20CMS.jpg?w=360",
  "iaaspaassaasunderstandingthedifferencestobetterchooseyourcloudsolution":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/IaaS%2c%20PaaS%2c%20Saas%20understanding%20differences.jpg?w=360",
  "howtojustifyandmeasureinvestmentinadxp":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/roi-digital-experience-platform-analysis.jpg?w=360",
  "underthehoodhydratingreactcomponentsinjava":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Under%20the%20Hood%20Hydrating%20React%20Components%20in%20Java.jpg?w=360",
  "transformyourcustomerportalintoarealpersonalizeddigitalexperience":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/customerportal-dxp.jpg?w=360",
  "whyjahiaisthebestplatformforinsurance":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/the%20best%20cms%20for%20insurances.png?w=360",
  "leveragingtheislandarchitectureinjahiacms":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/islands%20architecture%20schema.svg",
  "whatisanaccessiblecms":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/stylus-accessibility-test-tool.png?w=360",
  "whyoptforab2bcustomerportalthebenefitsandchallengesforyourcompany":
    "/files/live/sites/jahiacom/files/blog/portail-b2b/b2b-web-portal-for-digital-customer-relationships?w=360",
  "intranetvsextranetwhatarethedifferencesandhowdoyouchoose":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Intranet%20vs%20Extranet%20What%20are%20the%20differences.jpg?w=360",
  "hybridcmsbenefitsforcontentmanagementmergingthebestofbothsystems":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/hybrid.png?w=360",
  "globalaccessibilitydesigntipstomakeallyourwebsitescompliant":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/conception-site-web.png?w=360",
  "whatisacomposabledxp":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/DXP%20composable.jpg?w=360",
  "howtomakeawebsiteaccessibleguidelinesdesignpracticesandcompliancestrategies":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/accessibility-check-ascensus.png?w=360",
  "bestaccessibilitytestingtoolsforwebapplications":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/toolbox.jpeg?w=360",
  "dxpvscmswhichisrightforyou":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/DXP%20vs%20CMS%20Which%20is%20right%20for%20you.jpg?w=360",
  "top8alternativestoliferayin2025":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/top%208%20alternatives%20to%20liferay-min%20(1).jpg?w=360",
  "howtochooseadigitalexperienceplatformdxp":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/How%20to%20Choose%20a%20Digital%20Experience%20Platform%20(DXP).jpg?w=360",
  "whatisyourcustomerexperienceecosystem":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/What%20is%20your%20customer%20experience%20ecosystem.jpg?w=360",
  "howtodesignadigitalcustomerexperiencestrategy":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/digital%20customer%20experience%20strategy.jpg?w=360",
  "digitalassetmanagementvsdocumentmanagement":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/dam%20vs%20dms%20-%20jahia.jpg?w=360",
  "staticvsdynamicwebsitesheresthedifference":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/static%20vs%20dynamique%20websites%20-%20the%20difference%20-%20jahia.jpg?w=360",
  "whatisenterprisewebdevelopment":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/enterprise-web-development.jpeg?w=360",
  "whatiscontentasaservicecaas":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/jcontent-render2-resize1920x1275.jpg?w=360",
  "aiseoampcontentmarketinganalysisbykarineabbou":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/ia-seo-content-marketing-karine-abbou_en.jpg?w=360",
  "whatisthecontentlifecycle":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/jahia-content-editor-shared-field.png?w=360",
  "whatiscontentarchitectureandwhydoesitmatter":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/content-architecture.jpeg?w=360",
  "10effectivewaystoenhancewebaccessibility":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/accessibility-cms.png?w=360",
  "cmsreplatformingstrategiesprojectphasesandbenefits":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/change-CTO-mindset.jpg?w=360",
  "softwaresecuritybestpracticesforsecuringcms":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/security-first-development.png?w=360",
  "choosingthebestmultilingualcms":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Copy-to.png?w=360",
  "playbook3stepstointegrateaiintoyourcms":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/simplify-digital-transformation.jpg?w=360",
  "cmssecuritywhyitscrucialforyourbusiness":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cloud-security-low.png?w=360",
  "whyistherenoenterprisejavacmsbasedonspringframeworkorspringboot":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/tech-articles/6fcc0a46-7166-47c6-8593-0f96cc34316a.webp?w=360",
  "usingdigitalassetmanagementintegrations":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/gdpr-s.png?w=360",
  "headlessjavacmsindepthguidefordevelopers":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/headless-java-cms.webp?w=360",
  "toolsforanevergreenomnichannelstrategy":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Tools%20by%20stage%20in%20the%20omnichannel%20funnel.png?w=360",
  "createawebsitewithjavascriptthankstothenewfrontendstackinjahia82":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/jahia-press-release-8-2.jpg?w=360",
  "cloudcms3pointsofattentionforyourmigration":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/quote-blog-ebu-en.jpg?w=360",
  "jahiasportalmanagementguide":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Portal-Management-Systems.jpg?w=360",
  "userfriendlyjavascriptjavacmsdiscoverjahia82":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/overview-jahia-8_2-WYSIWYG.gif?w=360",
  "cmswithcloudhostingwhatmonitoringtoolsareneeded":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cloud.jpeg?w=360",
  "webprojectsteamwhichskillstorecruit":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Team%20work_1080px.png?w=360",
  "conversion3essentialstepsinyourpersonalizationstrategy":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/JAHIA_DXP_DATA_SCHEME.png?w=360",
  "howtoconnectsalesforcetoyourcmschallengesissues":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/integration_unomi_salesforce.jpg?w=360",
  "4stepstopersonalizeyourcustomerswebjourney":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/blog-perso.jpeg?w=360",
  "internalsearchengine4bestpracticestoimproveyourvisitorswebexperience":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/search.jpeg?w=360",
  "createadigitalexperiencewithyourcms":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/customer-digital-experience.webp?w=360",
  "ftrjahiareaffirmsitssecuritycommitmentswithamazonwebservicesaws":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/banner-ftr.png?w=360",
  "performanceofyourwebsiteyourimagesweighheavily":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/logo-scaleflex.webp?w=360",
  "boostyourseoperformancewithdirectaccesstosemjiinyourcms":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/logo-semji-seo.png?w=360",
  "keepickeradamintegratedintoyourcmsforbettercontentmanagement":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/logo-keepeek.webp?w=360",
  "opensourcecmswhatisitanddoineedit":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/open-source-cms.jpg?w=360",
  "thesupplierportalhowitboostsyourproductivityandstrengthensyourbusinessrelationships":
    "/files/live/sites/jahiacom/files/blog/portail-fournisseurs/supplier-web-portal-for-centralized-collaboration?w=360",
  "selfserviceportalwhatyouneedtoknowbeforelaunchingyourstrategy":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/portail-libre-service/libre-service-numerique.png?w=360",
  "howtochoosetheoptimalplatformtobuildyouronlineportalacomprehensiveguide":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/portal.png?w=360",
  "advantagesofheadlessenterprisecmsformultisiteapplications":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/why%20jahia.png?w=360",
  "understandingheadlesscmsacomprehensiveoverviewincludingprosconsandsuitability":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/understand.png?w=360",
  "howtodevelopadxpplatformwiththebestuxforbusinessusers":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/integrators2.png?w=360",
  "whatisadigitalexperienceplatformdxp":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/what-is-dxp-definition-infography-jahia.png?w=360",
  "jahiaisgoingcloudfirst":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cloud-first.png?w=360",
  "customizingpickersincontenteditor41":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/web-development.jpg?w=360",
  "howintegratorscandesigntheultimatecontentauthorexperienceinacmsintegratorstipspt1":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/integrators-blog.png?w=360",
  "whatdoourclientssayaboutusapec":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Apec%20Banner.png?w=360",
  "whatyouneedtoknowaboutsecuritywhenchoosingacloudcontentmanagementsystem":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cloud-security-low.png?w=360",
  "howtomigratetojahiacloudin5steps":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cloud.jpeg?w=360",
  "headlesscmswhichfeaturesformarketers":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/AdobeStock_394572656.jpeg?w=360",
  "5stepstosetupasitefactory":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/usine-a-sites.jpeg?w=360",
  "5waystoboostyourseoperformance":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/blog%20seo.png?w=360",
  "howtoapproachamigrationfromjahia7tojahia8":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/migration-v8%20.png?w=360",
  "digitalaccessibilitythefirststeptowardspersonalization":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/contentsquare.png?w=360",
  "jahiasnewextendableuserinterfaceuiinaction":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/UX.jpeg?w=360",
  "whatdoourclientssayaboutuslyonmétropolehabitat":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Lyon-Metropole.png?w=360",
  "jahiasopensourcedxpportaldevelopment":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Open-source-portals-java.jpg?w=360",
  "javabasedcmsbuiltonapachetomcat":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Java-based-CMS-Tomcat.jpg?w=360",
  "howtoelevateyourcxwithpersonascustomerjourneymapsandcontentauditing":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/How-to-Elevate-Your-CX-with-Personas.jpg?w=360",
  "cloudbasedcmsthebestwaytogoheadless":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Paas-vs-self-hosted.jpg?w=360",
  "5websitepersonalizationbestpracticesfreetool":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/website-personalization.jpg?w=360",
  "datafromthegroundup":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/data-from-the-ground-up.jpg?w=360",
  "choosingthebestcustomerdataplatformtopvendorscompared":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/best-cdps.jpg?w=360",
  "strengtheningyourconsumerbrandrelationshipstartswithfirstpartydata":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/concert-768722_1280.jpg?w=360",
  "cdpvsdmpkeydifferencesyouneedtoknow":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cdp-vs-dmp.jpg?w=360",
  "thetopcustomerdataplatformusecases":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/customer-data-platform-use-cases.jpg?w=360",
  "opensourcedxpthekeytogreatcustomerexperiences":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/open-source-digital-experience-platform.jpg?w=360",
  "5waysdamscanimprovedigitalexperiencecreation":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/place-of-work-women-3346613_1280.jpg?w=360",
  "breakingdownthethreetypesofcdpdata":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/3-types-of-cdp-data.png?w=360",
  "maximizeoperationaldatawithjahiasembeddedcdp":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/digital-marketing-1433427_1280.jpg?w=360",
  "astreamlinedmartechstackiscriticaltodigitalsuccess":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/corvette-2663762_1280.jpg?w=360",
  "thejourneyofadesignsystem":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/the-journey-of-a-design-system.jpg?w=360",
  "3ways2021willbedigitallydifferent":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/2021-trends.png?w=360",
  "whyyoushouldassessyourdigitalexperiencestackdxs":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/jahia_01.jpg?w=360",
  "whatisatruedxpsoftware":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/true-dxp.jpg?w=360",
  "dxpsandtheb2bleadfunnel":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/dxps-and-the-b2b-funnel-2.jpg?w=360",
  "jahiacmsanddxphipaacompliant":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/hipaa-compliant-blog.png?w=360",
  "isittimetoreevaluateyourdigitalstrategy":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/is-it-time-to-re-evaluate-your-digital-strategy.jpg?w=360",
  "thehighcostsofdxpsuites":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/the-high-cost-of-dxp-suites.png?w=360",
  "cmsvsdxpwhatsthedifference":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cms-vs-dxp.jpg?w=360",
  "whatisacontentmanagementsystem":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/what-is-a-cms.png?w=360",
  "itstimetostackupnotsuiteout":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/book-stacks.jpg?w=360",
  "innovationthroughiteration":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/jahia-screen.jpg?w=360",
  "creatingaprogressivewebappin2weekspart1":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/12-2019/Part%201.png?w=360",
  "creatingaprogressivewebappin2weekspart2":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/12-2019/Part%202.png?w=360",
  "whatisacdp":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/What%20Is%20A%20CDP%20blog%20image.jpg?w=360",
  "whatdowemeanbymakingdigitalsimpler":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Simple-series-1.jpg?w=360",
  "customerhighlightbnpparibas":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/BNP-Paribas-Blogpost-customer-highlight.jpg?w=360",
  "welcometojahiablogv15":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/-Jahia%20Blog-01.png?w=360",
  "theperformanceofyourwebsiteisakeyelementtoanalyse":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/pam/PAM-6.png?w=360",
  "yourdxpisavaluabledatasource":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/elk-4.png?w=360",
  "digitalmarketing7keypointstoconsiderwhenchoosingaweboptimizationtool":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/intergrated_DXP-12.jpg?w=360",
  "configuringawebservertosecurewebsitespoweredbydx":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/hacking_software_protection.jpg?w=360",
  "digitalizationthechallengeaheadforthetravelhospitalitysector":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/swimmingpool-resize1024x682.jpg?w=360",
  "easeyourauthorizationprocesswithoauthandsociallogin":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/banner-jahia-social-login.jpg?w=360",
  "usingdigitalexperiencemanagerandmarketingfactoryasheadlessproducts":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/dxp-3D.png?w=360",
  "interviewthreewavesofdigitalmarketingceodualgoalsandbattlestargalacticawisdom":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Three-waves.jpg?w=360",
  "moreinsightsaboutuserexperiencedesignanddevelopment":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/UXSummitFlorida.jpeg?w=360",
  "ondrivingdigitalleadershipthedisruptorcmo":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Disruptor-CMO.jpg?w=360",
  "newdisruptionindigitalmarketinglandscapedrivesinnovationinjahiabrandexperience":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/X-perience-Jahia.jpg?w=360",
  "letcustomersdecideinapushmepullmeworld":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/umbrella%20push%26pull-resize1000x419.jpg?w=360",
  "puttingthesocialincio":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/CIOblog-crop1001x435.png?w=360",
  "workplacewisdomtop10tipstotransformyourworklife":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/10tipsicon.jpg?w=360",
  "migrationdecmsgratuitepariamigrezrapidementvotresite":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/free-ai-cms-migration.jpg?w=360",
  "meilleuresalternativesàacquiaen2026comparatifdxp":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/alternatives-acquia-2026-jahia.png?w=360",
  "questcequunaicmscommentlechoisirpourvosworkflowsia":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/ai-cms.jpg?w=360",
  "personnalisationavecuncmsheadlesscommentdélivrerdesexpériencesréellementadaptatives":
    "/files/live/sites/jahiacom/files/social%20media/jahia-cms?w=360",
  "meilleuresalternativesàdrupalen2026cmsetdxpdentreprisecomparés":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/best-alternative-drupal.jpg?w=360",
  "commentcréerunextranetlesétapespourcadreretréussirvotreprojet":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/create-an-extranet.jpg?w=360",
  "solutionextranetchoisirlabonneplateformepourvosclientspartenairesetfournisseurs":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/web-portal.png?w=360",
  "iaagentiqueetgestiondecontenuscequevotrecmsdoitprévoiren2026":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/agentic-ai-in-content-management.jpg?w=360",
  "commentconstruireunestratégiedepersonnalisationdesiteweb":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/web-personalization-with-a-strong-cms.png?w=360",
  "personnalisationdesitewebstratégieetexemplespourboostervosconversions":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/website-personalization_-strategy-examples-best-practices.svg",
  "questcequunportailweb":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/12-2022/interface-portail-web.jpg?w=360",
  "questcequuncmsheadlesslavraiedéfinition":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/AdobeStock_239340937-copie.jpg?w=360",
  "rgpdetsouverainetépourquoilechoixdevotrecmscompte":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/GDPR-sovereignty/gdpr-sovereignty-why-your-choice-of-cms-matters.jpg?w=360",
  "top8desmeilleuresalternativesàadobeaemen2026":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Logos/aem-alternative-jahia.jpg?w=360",
  "jahiaausalonsouveraineténumérique2026standc13":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/salon-souverainete-conference.jpg?w=360",
  "cmsheadlessvscmstraditionnelavantagesinconvénientsetcasdusage":
    "/files/live/sites/jahiacom/files/blog/headless%20vs%20tradi/web-development-for-headless-and-traditional-cms?w=360",
  "jahiaparticipeaucrmday2026àparis":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cozendo-coffee-break-1177540.jpg?w=360",
  "top7desalternativesàsitecoreen2026":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Top%207%20alternatives%20to%20Sitecore%20in%202025.jpg?w=360",
  "depuislespacelanasapublieavecjahia":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/earth-nasa-artemis-ii-april-2026.jpg?w=360",
  "jahiarejointlafrenchtech":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/en_jahiaxfrenchtech_horizontale_1350x1080-enx.png?w=360",
  "migrationdesitewebenentreprisesécurisersonsitewebetsonseo":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cms-and-website-migration-jahia.jpg?w=360",
  "jahiafromthefieldnouveautésproduitetperspectives":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/banniere-generique-newsletter-produitx2.png?w=360",
  "questcequunsiteinternetdynamique":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/what%20is%20a%20dynamic%20website.jpg?w=360",
  "commentjaiutiliséliapourdévelopperunmodulejahiaenjavascriptenuntempsrecord":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/ia%20to%20develop%20jahia%20module%20in%20JS.jpg?w=360",
  "xpplatformlasolutionagileetsouverainepourdélivrerdesexpériencesdigitalesunifiées":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/xp%20platform.jpg?w=360",
  "9questionsàseposerpourchoisiruncmsmultisite":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/9%20questions%20to%20ask%20when%20choosing%20a%20multisite%20cms.jpg?w=360",
  "questcequelagestiondecontenudanslecloud":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/what%20is%20cloud%20content%20management%20-%20jahia.jpg?w=360",
  "toutcequevousdevezsavoirsurlescmscloud":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cloud-connect.jpg?w=360",
  "lapuissanceducmsmultisiteenjeuxavantagesetfonctionnalitésclés":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/The%20power%20of%20multisite%20CMS%20benefits-min.jpg?w=360",
  "questcequelagestiondesressourcesnumériquesdam":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Digital%20Asset%20Management%20(DAM).png?w=360",
  "enterprisecmsvssimplecmsquelleestladifférence":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/simple%20cms%20vs%20enterprise%20cms.jpg?w=360",
  "questcequuncmsdentreprisedéfinitionetfonctionnalités":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/what%20is%20enterprise%20cms.jpg?w=360",
  "10critèresstratégiquespourchoisirlemeilleurcmsdentreprise":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/10%20keys%20choosing%20the%20best%20CMS.jpg?w=360",
  "iaaspaassaascomprendrelesdifférencespourmieuxchoisirsasolutioncloud":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/IaaS%2c%20PaaS%2c%20Saas%20understanding%20differences.jpg?w=360",
  "commentjustifieretmesurerlinvestissementdansunedxp":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/roi-digital-experience-platform-analysis.jpg?w=360",
  "souslecapothydratationdescomposantsreactenjava":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Under%20the%20Hood%20Hydrating%20React%20Components%20in%20Java.jpg?w=360",
  "transformezvotreportailclientenunevéritableplateformedepersonnalisation":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/customerportal-dxp.jpg?w=360",
  "pourquoijahiaestlemeilleurcmspourlesassurances":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/the%20best%20cms%20for%20insurances.png?w=360",
  "tirerpartidelaconceptionenarchipeldansjahiacms":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/islands%20architecture%20schema.svg",
  "questcequuncmsaccessible":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/stylus-accessibility-test-tool.png?w=360",
  "pourquoiopterpourunportailclientenb2blesavantagesetlesenjeuxpourvotreentreprise":
    "/files/live/sites/jahiacom/files/blog/portail-b2b/b2b-web-portal-for-digital-customer-relationships?w=360",
  "intranetvsextranetquellesdifférencesetcommentchoisir":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Intranet%20vs%20Extranet%20What%20are%20the%20differences.jpg?w=360",
  "gouvernanceetrseleportailwebaucœurdespratiquesdurables":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/matrice-materialite-engie-gouvernance-rse.png?w=360",
  "cmshybridesdéfinitionsexplicationsetavantages":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/hybrid.png?w=360",
  "accessibilitéglobaleconseilsdeconceptionpourmettreenconformitétousvossitesweb":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/conception-site-web.png?w=360",
  "questcequunedxpcomposable":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/DXP%20composable.jpg?w=360",
  "accessibilitéetconceptiondesitewebmiseenconformitéourefonte":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/accessibility-check-ascensus.png?w=360",
  "siteweb12outilspourvostestsdaccessibilité":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/toolbox.jpeg?w=360",
  "dxpvscmslequelchoisir":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/DXP%20vs%20CMS%20Which%20is%20right%20for%20you.jpg?w=360",
  "top8desalternativesàliferayen2025":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/top%208%20alternatives%20to%20liferay-min%20(1).jpg?w=360",
  "commentchoisiruneplateformedexpériencedigitaledxp":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/How%20to%20Choose%20a%20Digital%20Experience%20Platform%20(DXP).jpg?w=360",
  "quelestvotreécosystèmedexpérienceclient":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/What%20is%20your%20customer%20experience%20ecosystem.jpg?w=360",
  "commentconstruireunebonnestratégiedexpérienceclientenligne":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/digital%20customer%20experience%20strategy.jpg?w=360",
  "digitalassetmanagementvsgestionélectroniquedesdocuments":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/dam%20vs%20dms%20-%20jahia.jpg?w=360",
  "sitesstatiquesvsdynamiquesquellesdifférences":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/static%20vs%20dynamique%20websites%20-%20the%20difference%20-%20jahia.jpg?w=360",
  "questcequeledéveloppementwebentreprise":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/enterprise-web-development.jpeg?w=360",
  "questcequelecontenuentantqueservicecaas":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/jcontent-render2-resize1920x1275.jpg?w=360",
  "iaseocontentmarketinganalysedekarineabbou":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/ia-seo-content-marketing-karine-abbou_en.jpg?w=360",
  "questcequelecycledevieducontenu":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/jahia-content-editor-shared-field.png?w=360",
  "questcequelarchitecturedecontenuetpourquoiestelleimportante":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/content-architecture.jpeg?w=360",
  "10façonsefficacesdaméliorervotreaccessibilitéweb":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/accessibility-cms.png?w=360",
  "iaconseilsdefrédériccavazzapourvotretransformationdigitale":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/frederic-cavazza-ia.jpg?w=360",
  "replatformingcmsstratégiesétapesetbénéfices":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/change-CTO-mindset.jpg?w=360",
  "sécuritélogiciellelesmeilleurespratiquespoursécuriserlescms":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/security-first-development.png?w=360",
  "choisirlemeilleurcmsmultilingue":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Copy-to.png?w=360",
  "playbook3étapespourintégrerliaàvotrecms":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/simplify-digital-transformation.jpg?w=360",
  "sécuritédessiteswebpourquoiestcecrucialpourvotreentreprise":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cloud-security-low.png?w=360",
  "pourquoiaucuncmsnestbasésurspringframeworkspringboot":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/tech-articles/6fcc0a46-7166-47c6-8593-0f96cc34316a.webp?w=360",
  "intégrationdamcommentconnectervossolutions":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/gdpr-s.png?w=360",
  "cmsjavaheadlessguidepourlesdéveloppeurs":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/headless-java-cms.webp?w=360",
  "outilspourunestratégieomnicanalepérenne":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Tools%20by%20stage%20in%20the%20omnichannel%20funnel.png?w=360",
  "développerunsitewebavecjavascriptaveclanouvellestackfrontenddejahia82":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/jahia-press-release-8-2.jpg?w=360",
  "cmscloud3pointsdattentionpourvotremigration":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/quote-blog-ebu-en.jpg?w=360",
  "quellesolutiondegestiondecontenupourunportailweb":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Portal-Management-Systems.jpg?w=360",
  "cmsjavascriptjavauserfriendlydécouvrezjahia82":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/overview-jahia-8_2-WYSIWYG.gif?w=360",
  "cmsavechébergementcloudquelsoutilsdesuivietdesurveillance":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cloud.jpeg?w=360",
  "projetwebquellescompétencesrecruterpourconstituervotreéquipe":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Team%20work_1080px.png?w=360",
  "conversion3étapesindispensablesàvotrestratégiedepersonnalisation":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/JAHIA_DXP_DATA_SCHEME.png?w=360",
  "commentconnectersalesforceàvotrecmsdéfisenjeux":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/integration_unomi_salesforce.jpg?w=360",
  "4étapespourpersonnaliserleparcourswebdevosclients":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/blog-perso.jpeg?w=360",
  "moteurderechercheinterne4bonnespratiquespouraméliorerlexpériencewebdevosvisiteurs":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/search.jpeg?w=360",
  "ftrjahiaréaffirmesesengagementsenmatièredesécuritéavecamazonwebserviceaws":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/banner-ftr.png?w=360",
  "performancesdevotresiteweblepoidsdesimages":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/logo-scaleflex.webp?w=360",
  "décuplezvosperformancesseogrâceàsemjienaccèsdirectdansvotrecms":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/logo-semji-seo.png?w=360",
  "keepickerundamintégréàvotrecmspourunemeilleuregestiondecontenus":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/logo-keepeek.webp?w=360",
  "cmsopensourcedéfinitionexplicationsetcomparaison":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/open-source-cms.jpg?w=360",
  "leportailfournisseurcommentilboostevotreproductivitéetrenforcevosrelationscommerciales":
    "/files/live/sites/jahiacom/files/blog/portail-fournisseurs/supplier-web-portal-for-centralized-collaboration?w=360",
  "portailselfservicenumériquecequilfautsavoiravantdelancervotrestratégie":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/portail-libre-service/libre-service-numerique.png?w=360",
  "commentchoisirlaplateformeoptimalepourconstruirevotreportailwebleguidecomplet":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/portal.png?w=360",
  "avantagesducmsheadlessenterprisepourlemultisite":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/why%20jahia.png?w=360",
  "ducmsheadlessaucmshybrideavantagesinconvénientsetpertinence":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/understand.png?w=360",
  "développeruneplateformedxpaveclameilleureuxpourlesutilisateursmétiers":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/integrators2.png?w=360",
  "questcequuneplateformedxpdigitalexperienceplateform":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/what-is-dxp-definition-infography-jahia.png?w=360",
  "jahiadevientcloudfirst":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cloud-first.png?w=360",
  "commentlesintégrateurspeuventilsoffriruneexpérienceoptimaleauxauteursdecontenudansuncmsastucespourlesintégrateurspt1":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/integrators-blog.png?w=360",
  "parolesdeclientapec":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Apec%20Banner.png?w=360",
  "commentbienévaluerlasécuritédevotreprochainsystèmedegestiondecontenucmsdanslecloud":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cloud-security-low.png?w=360",
  "commentmigrersurjahiaclouden5étapes":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cloud.jpeg?w=360",
  "headlesscmsquellesfonctionnalitéspourlesmarketers":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/AdobeStock_394572656.jpeg?w=360",
  "5étapespourmettreenplaceuneusineàsites":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/usine-a-sites.jpeg?w=360",
  "5actionspouroptimiservotreréférencementseo":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/blog%20seo.png?w=360",
  "commentaborderleprocessusdemigrationdejahia7àjahia8":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/migration-v8%20.png?w=360",
  "laccessibiliténumériquepremièreétapedelapersonnalisation":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/contentsquare.png?w=360",
  "jahia8unenouvelleinterfaceutilisateurpersonnalisable":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/UX.jpeg?w=360",
  "parolesdeclientslyonmétropolehabitat":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Lyon-Metropole.png?w=360",
  "développementdeportailopensourceavecjahia":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/Open-source-portals-java.jpg?w=360",
  "cdpetdmplesprincipalesdifférencesàconnaître":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cdp-vs-dmp.jpg?w=360",
  "principauxcasdusagedesplateformesdedonnéesclients":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/customer-data-platform-use-cases.jpg?w=360",
  "plateformesdexpériencedigitaleopensourceréinventezlexpérienceclient":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/open-source-digital-experience-platform.jpg?w=360",
  "maximisezvosdonnéesopérationnellesaveclacdpintégréedejahia":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/digital-marketing-1433427_1280.jpg?w=360",
  "votrestratégiedigitaleestcelemomentdelaredéfinir":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/is-it-time-to-re-evaluate-your-digital-strategy.jpg?w=360",
  "ladxppeutelleengendrerdescoûtscachés":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/the-high-cost-of-dxp-suites.png?w=360",
  "cmsvsdxpquellesdifférences":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/cms-vs-dxp.jpg?w=360",
  "unsystèmedegestiondecontenucmscestquoi":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/what-is-a-cms.png?w=360",
  "stackvssuitelèredelastackestarrivéehastalavistalessuites":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/book-stacks.jpg?w=360",
  "linnovationparitération":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/jahia-screen.jpg?w=360",
  "lesperformancesdevotresitewebsontunélémentcléàsurveiller":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/pam/PAM-6.png?w=360",
  "votredxpestuneprécieusesourcedinformations":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/elk-4.png?w=360",
  "marketingdigital7critèrescléspourvousaideràchoisirentresolutionsaasetoutilintégréàvotreplateformedxp":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/intergrated_DXP-12.jpg?w=360",
  "configurerunserveurwebpoursecuriserdessiteswebsousjahiadx":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/hacking_software_protection.jpg?w=360",
  "numérisationledéfiàvenirpourlesecteurtourismevoyagesloisirs":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/swimmingpool-resize1024x682.jpg?w=360",
  "intégrationdunsocialloginauseindesoutilsjahia":
    "https://cdfoqfniea.cloudimg.io/https://www.jahia.com/files/live/sites/jahiacom/files/blog/banner-jahia-social-login.jpg?w=360",
};

const titleKey = (title?: string) =>
  (title || "").toLocaleLowerCase().replace(/[^\p{L}\p{N}]/gu, "");

export const publicBlogImage = (title?: string, featured = false) => {
  const matchedSource = images[titleKey(title)];
  const source = matchedSource?.startsWith("/")
    ? `https://www.jahia.com${matchedSource}`
    : matchedSource;
  if (!source || !featured) return source;
  return source.replace(/([?&])w=\d+/, "$1w=1440");
};
