jahiacom_component=jahiacom - Components

jahiacom_helloWorld=Hello World
jahiacom_helloWorld.name=Name

jahiacom_helloCard=Hello Card
jahiacom_helloCard.title=Title
jahiacom_helloCard.illustration=Illustration
jahiacom_helloCard.illustration.code=A developer coding
jahiacom_helloCard.illustration.coffee=Buying coffee
jahiacom_helloCard.illustration.interface=Consulting an interface
jahiacom_helloCard.illustration.read=Looking at a bookshelf
jahiacom_helloCard.illustration.write=Writing with a typewriter

jahiacom_languageSwitcher=Language Switcher
